name: NESkvik CI

on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Ubuntu dependencies
      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libsdl2-dev wget
          sudo apt remove --purge --auto-remove cmake -y
          wget https://github.com/Kitware/CMake/releases/download/v3.31.4/cmake-3.31.4-linux-x86_64.sh
          sudo mkdir /opt/cmake
          sudo sh cmake-3.31.4-linux-x86_64.sh --prefix=/opt/cmake --skip-license
          sudo ln -sf /opt/cmake/bin/cmake /usr/local/bin/cmake

      # macOS dependencies
      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install sdl2 cmake

      # Windows dependencies
      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install mingw
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install sdl2

      # Configure
      - name: Configure CMake (Windows)
        if: matrix.os == 'windows-latest'
        run: cmake -S . -B build -DBUILD_DESKTOP=ON -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -G "MinGW Makefiles"

      - name: Configure CMake (others)
        if: matrix.os != 'windows-latest'
        run: cmake -S . -B build -DBUILD_DESKTOP=ON

      # Build
      - name: Build
        run: cmake --build build --config Release

      # Copy DLLs on Windows
      - name: Copy required DLLs (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          $mingwPath = "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"
          Copy-Item "$mingwPath\libgcc_s_seh-1.dll" -Destination build/Release
          Copy-Item "$mingwPath\libstdc++-6.dll" -Destination build/Release
          Copy-Item "$mingwPath\libwinpthread-1.dll" -Destination build/Release
          Copy-Item "thirdparty\SDL2\bin\SDL2.dll" -Destination build/Release

      # Upload artifacts
      - name: Upload artifact (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: NESkvikApp-Windows
          path: build/Release/*

      - name: Upload artifact (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: NESkvikApp-Linux
          path: build/NESkvikApp

      - name: Upload artifact (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: NESkvikApp-macOS
          path: build/NESkvikApp
