name: NESkvik CI

on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libsdl2-dev wget
          sudo apt remove --purge --auto-remove cmake -y
          wget https://github.com/Kitware/CMake/releases/download/v3.31.4/cmake-3.31.4-linux-x86_64.sh
          sudo mkdir /opt/cmake
          sudo sh cmake-3.31.4-linux-x86_64.sh --prefix=/opt/cmake --skip-license
          sudo ln -sf /opt/cmake/bin/cmake /usr/local/bin/cmake

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install mingw

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install sdl2 cmake

      - name: Configure CMake
        run: cmake -S . -B build -DBUILD_DESKTOP=ON

      - name: Build
        run: cmake --build build --config Release

      - name: Copy MinGW and SDL2 DLLs
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $mingwPath = (Get-Command g++.exe).Source | Split-Path
          Write-Host "Using MinGW path: $mingwPath"
          
          $neededDLLs = @(
            "libgcc_s_seh-1.dll",
            "libstdc++-6.dll",
            "libwinpthread-1.dll"
          )

          foreach ($dll in $neededDLLs) {
            $source = Join-Path $mingwPath $dll
            if (Test-Path $source) {
              Copy-Item $source -Destination build/Release
              Write-Host "Copied $dll"
            }
            else {
              Write-Host "Warning: $dll not found in $mingwPath"
            }
          }

          # Copy your SDL2.dll from thirdparty folder if you ship it
          Copy-Item "thirdparty/SDL2/bin/SDL2.dll" -Destination build/Release

      - name: Upload artifact (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: NESkvikApp-Windows
          path: build/Release/NESkvikApp.exe

      - name: Upload artifact (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: NESkvikApp-Linux
          path: build/NESkvikApp

      - name: Upload artifact (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: NESkvikApp-macOS
          path: build/NESkvikApp
